### PR TITLE
Fix Compilation!

### PR DESCRIPTION
**Pull request by pranav01**
I guess It was a Derp

### CODE REVIEW

**Comment by ateek-ujjawal** [comment]
Perfect fix, thank you!

**Comment by akhilnarang** [comment]
@pranav01  is the feature working now?

**Comment by pranav01** [comment]
@W4TCH0UT Ur Welcome Bro!
@akhilnarang  My zip isnt flashing donno why! :(

**Comment by akhilnarang** [comment]
@pranav01 I told you what to do on pm

**Pull request merged**
